### ISSUE TITLE
Pull-through mirror issues

### ISSUE THREAD

**Issue by MaxOinRU** [boring-registry/boring-registry#187]
Hi, 
I was searching for a terraform registry project with "Pull-through mirror" feature. But with docker/helm found only `boring-registry` and have issues with it :)

I use `boring-registry` in `docker swarm` stack with compose file. Also i use `traefik` as reverse-proxy. I set `--network-mirror-pull-through=true`, but when tried `terraform init` i got this error:

```shell
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider terraform-provider-openstack/openstack: provider registry.terraform.io/terraform-provider-openstack/openstack was not
│ found in any of the search locations
│ 
│   - provider mirror at https://boring-registry.my.test.ru/v1/mirror/
╵
```

Container in DEBUG logs also have error:
```shell
time=2024-07-16T11:23:50.537Z level=ERROR source=/go/src/github.com/boring-registry/boring-registry/pkg/mirror/middleware.go:38 msg="failed to list provider versions" hostname=646f3605424a op=ListProviderVersions provider.hostname=registry.terraform.io provider.namespace=terraform-provider-openstack provider.name=openstack err="failed to find matching providers: hostname=registry.terraform.io, namespace=terraform-provider-openstack, name=openstack"
```

What i did wrong or it`s a BUG?

`boring-registry` compose-file:
```yml
version: "3.8"

networks:
  proxy:
    external: true
  internal:
    external: false

services:     
  boring-registry:
    image: ghcr.io/boring-registry/boring-registry:v0.14.0
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.boring-registry.rule=Host(`boring-registry.my.test.ru`)
        - traefik.http.services.boring-registry.loadBalancer.server.port=5601
    environment:
      - BORING_REGISTRY_DEBUG=true
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_DEFAULT_REGION=xxx
      - AWS_ENDPOINT_URL=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
    networks:
      - proxy
      - internal
    command: server --storage-s3-bucket=test-shared \
                    --network-mirror-pull-through=true \
                    --auth-static-token "xxx"
```

.terraformrc file:
```hcl
provider_installation {
  network_mirror {
     url = "https://boring-registry.my.test.ru/v1/mirror/"
  }
}
credentials "boring-registry.my.test.ru" {
  token = "xxx"
}
```
